const trips=[
{id:'santorini',destination:'Greece',circle:'Girls',style:'Relaxation',month:'nov',title:'Santorini Slow Escape',dates:'Nov 8–13 · 6 days',price:'$1,150',spots:'3 spots left',organizer:'Maya Hassan',image:'assets/santorini.png',description:'Golden sunsets, hidden beaches and long dinners across Santorini with a small girls-only circle.'},
{id:'bali',destination:'Indonesia',circle:'Mixed',style:'Adventure',month:'oct',title:'Bali Beyond the Guidebook',dates:'Oct 18–24 · 7 days',price:'$1,280',spots:'4 spots left',organizer:'Noah Kim',image:'assets/bali.png',description:'Rice terraces, jungle trails and island rituals with a curious mixed travel circle.'},
{id:'cappadocia',destination:'Turkey',circle:'Guys',style:'Culture',month:'dec',title:'Cappadocia Sunrise Club',dates:'Dec 3–7 · 5 days',price:'$890',spots:'Trip full',organizer:'Omar Selim',image:'assets/cappadocia.png',description:'Cave towns, local tables and unforgettable balloon sunrises with a guys travel circle.'}];
const $=s=>document.querySelector(s),grid=$('#tripGrid'),summary=$('#resultSummary'),empty=$('#emptyState');
const filters=['destination','circle','style','date'].map(id=>document.getElementById(id));
const card=t=>`<article class="trip-card"><button class="card-image" data-open-trip="${t.id}" aria-label="View ${t.title}"><img src="${t.image}" alt="${t.title}"/><span class="circle-badge">${t.circle} circle</span></button><div class="card-body"><div class="card-top"><span>${t.destination} · ${t.style}</span><span class="spots ${t.spots==='Trip full'?'full':''}">${t.spots}</span></div><h3>${t.title}</h3><p>${t.dates}</p><div class="card-footer"><p><b>${t.price}</b> / person</p><button data-open-trip="${t.id}">${t.spots==='Trip full'?'Join waitlist':'View trip'}</button></div></div></article>`;
function render(items=trips){grid.innerHTML=items.map(card).join('');empty.hidden=!!items.length;grid.hidden=!items.length;summary.textContent=items.length?`${items.length} ${items.length===1?'trip':'trips'} matching your preferences`:'No matching trips'}
$('#searchForm').addEventListener('submit',e=>{e.preventDefault();const[d,c,s,m]=filters.map(f=>f.value);render(trips.filter(t=>(d==='all'||t.destination===d)&&(c==='all'||t.circle===c)&&(s==='all'||t.style===s)&&(m==='all'||t.month===m)));$('#trips').scrollIntoView({behavior:'smooth'})});
$('#clearFilters').addEventListener('click',()=>{filters.forEach(f=>f.value='all');render()});
const tripDialog=$('#tripDialog');document.addEventListener('click',e=>{const x=e.target.closest('[data-open-trip]');if(!x)return;const t=trips.find(v=>v.id===x.dataset.openTrip);$('#dialogImage').src=t.image;$('#dialogImage').alt=t.title;$('#dialogKicker').textContent=`${t.circle} circle · ${t.style}`;$('#dialogTitle').textContent=t.title;$('#dialogDescription').textContent=t.description;$('#dialogDates').textContent=t.dates;$('#dialogPrice').textContent=`${t.price} / person`;$('#dialogSpots').textContent=t.spots;$('#dialogOrganizer').textContent=t.organizer;$('.join-btn').textContent=t.spots==='Trip full'?'Join Waitlist':'Join Trip';tripDialog.showModal()});
$('.close-btn').onclick=()=>tripDialog.close();const joinDialog=$('#joinDialog');$('.join-btn').onclick=()=>{tripDialog.close();joinDialog.showModal()};$('.close-join').onclick=()=>joinDialog.close();
$('#joinForm').addEventListener('submit',e=>{e.preventDefault();e.currentTarget.hidden=true;$('.success').hidden=false});$('.success-close').onclick=()=>{joinDialog.close();$('#joinForm').hidden=false;$('.success').hidden=true;$('#joinForm').reset()};
$('.menu-btn').onclick=e=>{const n=$('nav');n.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',n.classList.contains('open'))};render();
